LANGUAGE_EXTENSION = {
    'Ada': 'ada',
    'Algol 68': '',
    'Assembly (32bit)': 'asm',
    'Assembly (64bit)': 'asm',
    'Bash': 'sh',
    'Befunge': '',
    'Boo': 'boo',
    'Brainf**k': 'bf',
    'C': 'c',
    'C (Clang)': 'clang',
    'C# 6.0': 'cs',
    'C++': 'cpp',
    'C++ (Clang)': 'clang',
    'C++11': 'cpp',
    'C++11 (Clang)': 'clang',
    'C++14': 'cpp',
    'C++14 (Clang)': 'clang',
    'C++17': 'cpp',
    'C++17 (Clang)': 'clang',
    'C++2a': 'cpp',
    'C++2a (Clang)': 'clang',
    'C11': 'c',
    'C11 (Clang)': 'clang',
    'Cobol': 'cbl',
    'Cobra': '',
    'D': 'd',
    'F#': 'fs',
    'Fortran': 'f',
    'Go': 'go',
    'Golfscript': 'gs',
    'Haxe': '',
    'INTERCAL': '',
    'Java': 'java',
    'Java (OpenJDK)': 'java',
    'Java 11': 'java',
    'Kotlin (JVM)': 'kt',
    'Kotlin (Native)': 'kt',
    'LOLCODE': '',
    'Lua': 'lua',
    'OCaml': 'ml',
    'Objective-C': 'm',
    'Objective-C++': 'mm',
    'PHP': 'php',
    'Pascal': 'pp',
    'Perl': 'pl',
    'Pike': '',
    'PyPy2': 'py',
    'PyPy3': 'py',
    'Python 2': 'py',
    'Python 3': 'py',
    'R': 'r',
    'Rhino': '',
    'Ruby 1.8': 'rb',
    'Ruby 2.5': 'rb',
    'Rust': 'rs',
    'Rust 2018': 'rs',
    'Scheme': 'scm',
    'Swift': 'swift',
    'Tcl': 'tcl',
    'Text': 'txt',
    'VB.NET 4.0': 'vb',
    'Whitespace': 'txt',
    'awk': 'awk',
    'bc': 'txt',
    'node.js': 'js',
    'sed': 'txt',
    '아희': 'aheui',
}